### ISSUE TITLE
intelliSense not working

### ISSUE THREAD

**Issue by ShaquibKhanhub** [tailwindlabs/tailwindcss-intellisense#1067]
Type: <b>Bug</b>

it's been a very long time since this extention not working when im using tailwindcss in my projects it's not giving any class suggestion  tailwind.congif file is correct and also the index.css file but still it's not working 

Extension version: 0.12.11
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.08GB free)|
|Process Argv|--crash-reporter-id 0832baec-6eab-4cf3-9a6c-1f692fca4a74|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31162478
iconenabled:31158251

```

</details>

**Comment by ShaquibKhanhub** [comment]
this is the user settings.json file.

{
  "emmet.useInlineCompletions": true,
  "explorer.confirmDelete": false,
  "liveServer.settings.AdvanceCustomBrowserCmdLine": "chrome",
  "liveServer.settings.ignoreFiles": [
    ".vscode/**",
    "**/*.scss",
    "**/*.sass",
    "**/*.ts"
  ],
  "liveServer.settings.port": 0,
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.wordWrap": "on",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "code-runner.runInTerminal": true,
  "editor.accessibilitySupport": "on",
  "[jsonc]": {
    "editor.quickSuggestions": {
      "other": "inline"
    }
  },
  "[json]": {
    "editor.suggest.snippetsPreventQuickSuggestions": true
  },
  "editor.quickSuggestions": {
    "strings": "inline"
  },
  "tabnine.experimentalAutoImports": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.fontLigatures": true,
  "editor.fontFamily": "'cascadia code',Consolas,'Courier New',monospace",
  "remote.SSH.remotePlatform": {
    "sandbox.7r4v79.csb": "linux"
  },
  "[css]": {
    "editor.defaultFormatter": "vscode.css-language-features"
  },
  "files.autoSave": "afterDelay",
  "quokka.compactMessageOutput": true,
  "tabnine.debug": true,
  "tabnine.disableFileRegex": [],
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "terminal.integrated.env.windows": {},
  "console-ninja.toolsToEnableSupportAutomaticallyFor": {
    "live-server-extension": true,
    "live-preview-extension": true
  },
  "liveServer.settings.donotVerifyTags": true,
  "editor.cursorBlinking": "expand",
  "editor.cursorSmoothCaretAnimation": "on",
  "terminal.integrated.env.linux": {},
  "git.autofetch": true,
  "gitlens.graph.layout": "editor",
  "liveServer.settings.ChromeDebuggingAttachment": false,
  "liveServer.settings.CustomBrowser": "microsoft-edge",
  "console-ninja.featureSet": "Community",
  "nxConsole.showNodeVersionOnStartup": false,
  "terminal.integrated.enableMultiLinePasteWarning": false,
  "files.exclude": {
    "**/.git": false,
    "**/.trunk/*actions/": true,
    "**/.trunk/*logs/": true,
    "**/.trunk/*notifications/": true,
    "**/.trunk/*out/": true,
    "**/.trunk/*plugins/": true
  },
  "html-to-css-autocompletion.getSelectorsFromFileTypes": ["html", "php"],
  "terminal.integrated.fontWeightBold": "bold",
  "terminal.integrated.cursorBlinking": true,
  "window.zoomLevel": 1,
  "editor.fontSize": 16,
  "workbench.editorAssociations": {
    "*.md": "default"
  },
  "accessibility.signals.lineHasError": {
    "sound": "off"
  },
  "accessibility.signals.lineHasFoldedArea": {
    "sound": "off"
  },
  "accessibility.signals.lineHasBreakpoint": {
    "sound": "off"
  },
  "accessibility.signals.lineHasInlineSuggestion": {
    "sound": "off"
  },
  "accessibility.signals.onDebugBreak": {
    "sound": "off"
  },
  "accessibility.signals.noInlayHints": {
    "sound": "off"
  },
  "accessibility.signals.taskCompleted": {
    "sound": "off"
  },
  "accessibility.signals.taskFailed": {
    "sound": "off"
  },
  "accessibility.signals.notebookCellCompleted": {
    "sound": "off"
  },
  "accessibility.signals.notebookCellFailed": {
    "sound": "off"
  },
  "accessibility.signals.diffLineInserted": {
    "sound": "off"
  },
  "accessibility.signals.diffLineDeleted": {
    "sound": "off"
  },
  "accessibility.signals.diffLineModified": {
    "sound": "off"
  },
  "javascript.updateImportsOnFileMove.enabled": "always",
  "github.copilot.editor.enableAutoCompletions": true,
  "files.watcherExclude": {
    "**/.trunk/*actions/": true,
    "**/.trunk/*logs/": true,
    "**/.trunk/*notifications/": true,
    "**/.trunk/*out/": true,
    "**/.trunk/*plugins/": true
  },
  "autoimport.doubleQuotes": true,
  "workbench.colorTheme": "Ayu Light",
  "vscode-edge-devtools.webhintInstallNotification": true,
  "[typescriptreact]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "terminal.integrated.defaultProfile.windows": "Git Bash",
  "cSpell.userWords": ["cloudinary", "Shaquib"],
  "tailwindCSS.experimental.configFile": "./tailwind.config.js",
  "tailwindCSS.includeLanguages": {
    "javascript": "javascript",
    "javascriptreact": "html",
    "typescript": "javascript",
    "typescriptreact": "html"
  },
  "workbench.iconTheme": "material-icon-theme"
}

**Comment by lts20050703** [comment]
@ShaquibKhanhub The latest version is 0.13.44, is there any reasons you're not using the latest version?

**Comment by lts20050703** [comment]
Oh that's really weird, I checked https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss and it says 0.13.44, guess there's something wrong going on here

**Comment by ShaquibKhanhub** [comment]
> @ShaquibKhanhub The latest version is 0.13.44, is there any reasons you're not using the latest version?

I'm facing this issue from past six month you can say when the version was 0.11 something and this extension is in auto update and yesterday only i have uninstall the extension and reinstall it.

**Comment by ShaquibKhanhub** [comment]
> Oh that's really weird, I checked https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss and it says 0.13.44, guess there's something wrong going on here

Yup i tried to uninstall my vscode and reinstall but it's still not working i thought there something wrong with the vscode and also uninstall my several extension that might be colliding with the tailwind intellisense but still not working I'm not getting any suggestions and when i hover over any classes it's also not showing the class details.

**Comment by thecrypticace** [comment]
> @ShaquibKhanhub The latest version is 0.13.44, is there any reasons you're not using the latest version?

The latest stable version is 0.12.x — 0.13.x is a pre-release. As a convention most VSCode extensions use odd version numbers for pre-releases and even ones for stable releases. There's little difference between the two at the moment though.

**Comment by thecrypticace** [comment]
@ShaquibKhanhub Can you provide logs for your project? Open the command palette and run "Tailwind CSS: Show Output"?

**Comment by ShaquibKhanhub** [comment]
as earlier I have said that I'm facing this issue from past 6 months and for the 0.13v I'm currently using this version but still not working.

**Comment by ShaquibKhanhub** [comment]
@thecrypticace showing this I thing there's something wrong .

Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"e:\\mern-app\\tinder-clone","config":"E:/mern-app/tinder-clone/tailwind.config.js","selectors":[{"priority":0,"pattern":"E:/mern-app/tinder-clone/**"}],"user":true,"tailwind":{"version":"3.4.4","features":["layer:base","separator:root","content-list","jit","css-at-config-as-project","relative-content-paths","transpiled-configs"],"isDefaultVersion":true}}]
[Global] Preparing projects...
[Global] Adding watch patterns: E:/mern-app/tinder-clone/tailwind.config.js, E:/mern-app/tinder-clone, E:/mern-app, E:/
[Global] Initializing projects...
[tailwind.config.js] Initializing...
[Error - 11:10:01 AM] Tailwind CSS: ENOENT: no such file or directory, stat 'E:\mern-app\tinder-clone\tailwind.config.js'
Error: ENOENT: no such file or directory, stat 'E:\mern-app\tinder-clone\tailwind.config.js'
    at statSync (node:fs:1667:25)
    at t.statSync (node:electron/js2c/node_init:2:5052)
    at c:\Users\ASIF\.vscode\extensions\bradlc.vscode-tailwindcss-0.13.45\dist\tailwindServer.js:1291:7853
    at Array.map (<anonymous>)
    at fue (c:\Users\ASIF\.vscode\extensions\bradlc.vscode-tailwindcss-0.13.45\dist\tailwindServer.js:1291:7840)
    at x (c:\Users\ASIF\.vscode\extensions\bradlc.vscode-tailwindcss-0.13.45\dist\tailwindServer.js:1291:10697)
    at Object.D [as tryInit] (c:\Users\ASIF\.vscode\extensions\bradlc.vscode-tailwindcss-0.13.45\dist\tailwindServer.js:1291:10146)
    at eS._initFolder (c:\Users\ASIF\.vscode\extensions\bradlc.vscode-tailwindcss-0.13.45\dist\tailwindServer.js:1293:23308)
    at async Promise.allSettled (index 0)
    at async eS._init (c:\Users\ASIF\.vscode\extensions\bradlc.vscode-tailwindcss-0.13.45\dist\tailwindServer.js:1293:18034)
[Global] Initialized 1 projects

**Comment by ShaquibKhanhub** [comment]
@thecrypticace thanks it's working now i just add these code configuration inside my settings.json .
{
  "tailwindCSS.includeLanguages": {
    "plaintext": "html"
  },
  "tailwindCSS.experimental.classRegex": [
    ["class\\s*?=\\s*?\"([^\"]*)\"", 1],
    ["className\\s*?={\\s*?\"([^\"]*)\"", 1]
  ],

  "tailwindCSS.projects": [
    {
      "folder": "./",
      "config": "./tailwind.config.js"
    }
  ]
}
if anyone facing issue like mine just provide these like of code it will work but to make it **globally**, they have to add this inside **user.settings.json**  
**Open VSCode.**
Go to User Settings by pressing **Ctrl + ,** **(or Cmd + ,** on Mac).
Click on the **{}** icon in the top right to open the **settings.json** file.
Replace the existing content with the provided configuration or merge it with your current settings.
Save the file.
Happy coding!

**Comment by cocoich** [comment]
```json
"tailwindCSS.projects": [
  {
    "folder": "./",
    "config": "./tailwind.config.js"
  }
]
```

```
[Error - 11:10:01 AM] Tailwind CSS: ENOENT: no such file or directory, stat 'E:\mern-app\tinder-clone\tailwind.config.js'
Error: ENOENT: no such file or directory, stat 'E:\mern-app\tinder-clone\tailwind.config.js'
```


it looks doesn't exists.
@ShaquibKhanhub can you provide project-root directory filename?

**Comment by ShaquibKhanhub** [comment]
> ```json
> "tailwindCSS.projects": [
>   {
>     "folder": "./",
>     "config": "./tailwind.config.js"
>   }
> ]
> ```
> 
> ```
> [Error - 11:10:01 AM] Tailwind CSS: ENOENT: no such file or directory, stat 'E:\mern-app\tinder-clone\tailwind.config.js'
> Error: ENOENT: no such file or directory, stat 'E:\mern-app\tinder-clone\tailwind.config.js'
> ```
> 
> it looks doesn't exists. @ShaquibKhanhub can you provide project-root directory filename?

thank you but now the extension is finally working.

**Comment by thecrypticace** [comment]
Glad you got it working 👍
