### ISSUE TITLE
Extension fails on versions newer than 0.4.0 when project files are on a linux VM, and VSCode on Windows 10

### ISSUE THREAD

**Issue by ssuvanto** [tailwindlabs/tailwindcss-intellisense#257]
My code lives on a linux VM and I'm accessing files through Windows networking.

Version 0.4.0 of the extension works. Anything after that fails. This is what I get with the latest version:

```
Found Tailwind config file: \vm.domain.io\sites\testproject\tailwind.config.js
Failed to initialise: Error: Cannot find module 'tailwindcss/package.json'
Require stack:
- \\vm.domain.io\sites\vm.domain.io\sites\testproject\noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at a (c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:38328)
    at s (c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:38437)
    at e.exports (c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:38459)
    at resolve (c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:156523)
    at c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:161240
    at c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:156465
    at L (c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:156531)
    at L (c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:156750)
    at c:\Users\MyUser\.vscode\extensions\bradlc.vscode-tailwindcss-0.5.8\dist\server\index.js:13:161182 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '\\\\vm.domain.io\\sites\\vm.domain.io\\sites\\testproject\\noop.js'
  ]
}
```

I've tried copying the project files directly onto Windows and that makes the extension load just fine.

I suspect the problem has to do with the 0.4.0 -> 0.4.1 changes that were made to discovering the config file and tailwindcss package. Maybe even the normalize-path package messing up the double backslash needed at the start of the file path?

**Comment by ssuvanto** [comment]
I'm able to get around the issue by using the Remote SSH feature of VSCode rather than using the VM files through Samba/Windows networking file system.

I may adopt this workflow but it might still be worth it to fix the issue.
You can close the issue if you don't think so.

**Comment by bradlc** [comment]
Going to close this as we have no plans to support projects where the files are accessed via Windows networking. VS Code itself does not support watching files over network drives.
