### ISSUE TITLE
Support Windi CSS compiler

### ISSUE THREAD

**Issue by Miaourt** [tailwindlabs/tailwindcss-intellisense#264]
Hello !
There's another implementation of TailwindCSS called [windicss](https://github.com/voorjaar/windicss), that offer many advantages for some use cases like mine.

I wondered if it could be supported as a backend for this TailwindCSS intellisense extension, seems it seems to rely only the official package for now :)

I'm getting this error :
```
Found Tailwind config file: c:\Users\leo\Projets\cervo-svelte\tailwind.config.js
Failed to initialise: Error: Cannot find module 'tailwindcss/package.json'
Require stack:
- c:\Users\leo\Projets\cervo-svelte\noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at a (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:38328)
    at s (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:38437)
    at e.exports (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:38459)
    at resolve (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156730)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:161602
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156672
    at L (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156738)
    at L (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156957)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:161544 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'c:\\Users\\leo\\Projets\\cervo-svelte\\noop.js' ]
}
(node:3132) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'classNames' of undefined
    at Te (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:116588)
    at Ge (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124048)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124397
    at Array.forEach (<anonymous>)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124368
    at Array.forEach (<anonymous>)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124333
(node:3132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm also opening an issue on their end, since it might definitely need some cooperation between the two projects : https://github.com/voorjaar/windicss/issues/13

**Comment by bradlc** [comment]
Hey @Miaourt. We won't be adding support for Windi CSS as it is not a goal of Tailwind CSS IntelliSense to support things that aren't Tailwind CSS. Sorry about that but hopefully that makes sense 👍

**Comment by benwoodward** [comment]
Please reconsider this. Windi, as far as I understand it, can be seen as an alternative compiler for Tailwind CSS styles. 

When using `tailwindcss-intellisense` with Windi I get the following error:

`"Tailwind CSS: addDynamic is not a function\nTypeError: addDynamic is not a function`.

So presumably `tailwindcss-intellisense` is generating suggestions for any styles that have been added via the config and/or plugins. Assuming this is the case, I'd be happy if there was a simple config option for `tailwindcss-intellisense` called `usingWindi: Bool`, and if `true`, then `tailwindcss-intellisense` just ignores what's in the config completely and then just works as normal.

**Comment by polyzen** [comment]
https://github.com/windicss/windicss-intellisense
