### ISSUE TITLE
Not working with postcss7-compat

### ISSUE THREAD

**Issue by szdmr** [tailwindlabs/tailwindcss-intellisense#306]
If `@tailwindcss/postcss7-compat` is installed instead of the regular one it fails to resolve Tailwind. 
```
Error: Cannot find module 'tailwindcss/package.json'
Require stack:
- /Users/YYY/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1019:15)
    at a (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:38328)
    at s (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:38437)
    at e.exports (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:38459)
    at resolve (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:156762)
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:161644
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:156704
    at L (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:156770)
    at L (/Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:156989)
    at /Users/XXX/.vscode/extensions/bradlc.vscode-tailwindcss-0.5.10/dist/server/index.js:13:161586
```
I think these needs to be fixed: [1](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/3a01ebd1731374a3abd9bf16fd6d757f34d17b98/packages/tailwindcss-intellisense/src/class-names/resolveConfig.js#L16) [2](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/3a01ebd1731374a3abd9bf16fd6d757f34d17b98/packages/tailwindcss-intellisense/src/class-names/getPlugins.js#L9) [3](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/8fce24db9c480a9615e175fb3acaac91f7a0a7c1/packages/tailwindcss-intellisense/src/class-names/index.js#L261) [4](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/8fce24db9c480a9615e175fb3acaac91f7a0a7c1/packages/tailwindcss-intellisense/src/class-names/index.js#L278)

**Comment by bradlc** [comment]
We can probably improve this, but for now it should work fine if you install `@tailwindcss/postcss7-compat` as `tailwindcss`:

```
npm install tailwindcss@npm:@tailwindcss/postcss7-compat
```

**Comment by bradlc** [comment]
I looked into this and it isn't going to be possible to support the case where `@tailwindcss/postcss7-compat` is installed unaliased, so I'm going to close this.
