### ISSUE TITLE
Tailwind CSS: variantsValue is not iterable when extending colors.

### ISSUE THREAD

**Issue by mrmurphy** [tailwindlabs/tailwindcss-intellisense#336]
Hi there, looks like I'm running into #309 again.

Stack trace with versions of postcss and tailwind:
```
Loaded postcss v8.2.13: /Users/blah/assets/node_modules/postcss
Loaded tailwindcss v2.1.2: /Users/blah/assets/node_modules/tailwindcss
[Error - 6:31:36 AM] Tailwind CSS: variantsValue is not iterable
TypeError: variantsValue is not iterable
    at /Users/blah/assets/node_modules/tailwindcss/lib/util/resolveConfig.js:219:43
    at baseMergeDeep (/Users/blah/assets/node_modules/lodash/_baseMergeDeep.js:42:7)
    at /Users/blah/assets/node_modules/lodash/_baseMerge.js:27:7
    at /Users/blah/assets/node_modules/lodash/_createBaseFor.js:17:11
    at baseMerge (/Users/blah/assets/node_modules/lodash/_baseMerge.js:24:3)
    at /Users/blah/assets/node_modules/lodash/mergeWith.js:36:3
    at /Users/blah/assets/node_modules/lodash/_createAssigner.js:30:9
    at apply (/Users/blah/assets/node_modules/lodash/_apply.js:15:25)
    at /Users/blah/assets/node_modules/lodash/_overRest.js:32:12
    at mergeVariantExtensions (/Users/blah/assets/node_modules/tailwindcss/lib/util/resolveConfig.js:218:33)
```

tailwind.config.js:

```
const colors = require("tailwindcss/colors");

module.exports = {
  purge: [
    "../lib/**/*.ex",
    "../lib/**/*.leex",
    "../lib/**/*.eex",
    "./js/**/*.js",
  ],
  mode: "jit",
  darkMode: "media", // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {
      colors: {
        "light-blue": colors.lightBlue,
        cyan: colors.cyan,
        pink: colors.pink,
        rose: colors.rose,
        fuchia: colors.fuchia,
        amber: colors.amber,
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
```

Thank you!

**Comment by bradlc** [comment]
I think this error is expected. You have your colors under `variants.extend` when they should be under `theme.extend`:

```js
const colors = require("tailwindcss/colors");

module.exports = {
  purge: [
    "../lib/**/*.ex",
    "../lib/**/*.leex",
    "../lib/**/*.eex",
    "./js/**/*.js",
  ],
  mode: "jit",
  darkMode: "media", // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        "light-blue": colors.lightBlue,
        cyan: colors.cyan,
        pink: colors.pink,
        rose: colors.rose,
        fuchia: colors.fuchia,
        amber: colors.amber,
      },
    },
  },
  variants: {
    extend: {
      //
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
```

**Comment by mrmurphy** [comment]
Oh wow, of course. I'm so sorry about that.
