### ISSUE TITLE
Error popup: TailwindCSS: variantsValue is not iterable

### ISSUE THREAD

**Issue by lemurriot** [tailwindlabs/tailwindcss-intellisense#352]
Recently I've been getting a pop up:"Tailwind CSS: variantsValue is not iterable" in vsCode. 

I can't see what's wrong, here is my tailwind.config.js:
```const { blueGray } = require('tailwindcss/colors');

const viewHeights = {
  '1/4-screen': '25vh',
  '1/2-screen': '50vh',
  '3/4-screen': '75vh',
  '4/5-screen': '80vh',
}

module.exports = {
  purge: {
    enabled: true,
    content: [
      './react/**/*.js',
      './react/**/*.jsx',
    ]
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        blueGray,
      },
      fontSize: {
        'xxs': ['0.65rem', '0.85rem'], // [fontSize, lineHeight]
      },
      minWidth: {
        '4': '1rem',
        '8': '2rem',
        '900px': '900px',
        '2/5': '40%',
        '1/2': '50%',
      },
      maxWidth: {
        '40': '10rem',
        '60': '15rem',
        '2/5': '40%',
        '1/2': '50%',
      },
      height: {
        '15/100': '15%',
      },
      minHeight: {
        ...viewHeights,
        '48': '12rem',
      },
      maxHeight: {
        ...viewHeights,
      },
    },
  },
  variants: {
    extend: {
      opacity: ['disabled'],
      textColor: ['disabled'],
      borderColor: ['disabled'],
      backgroundColor: ['disabled'],
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

Logs from the vsCode output:
```Found Tailwind CSS config file: /root/my-repo/tailwind.config.js
Loaded postcss v8.3.4: /root/my-repo/node_modules/postcss
Loaded tailwindcss v2.1.4: /root/my-repo/node_modules/tailwindcss
[Error - 12:50:05 AM] Tailwind CSS: variantsValue is not iterable
TypeError: variantsValue is not iterable
    at /root/my-repo/node_modules/tailwindcss/lib/util/resolveConfig.js:219:43
    at baseMergeDeep (/root/my-repo/node_modules/lodash/_baseMergeDeep.js:42:7)
    at /root/my-repo/node_modules/lodash/_baseMerge.js:27:7
    at /root/my-repo/node_modules/lodash/_createBaseFor.js:17:11
    at baseMerge (/root/my-repo/node_modules/lodash/_baseMerge.js:24:3)
    at /root/my-repo/node_modules/lodash/mergeWith.js:36:3
    at /root/my-repo/node_modules/lodash/_createAssigner.js:30:9
    at apply (/root/my-repo/node_modules/lodash/_apply.js:15:25)
    at /root/my-repo/node_modules/lodash/_overRest.js:32:12
    at mergeVariantExtensions (/root/my-repo/node_modules/tailwindcss/lib/util/resolveConfig.js:218:33)
```

**Comment by lemurriot** [comment]
I updated my package.json and restarted vsCode, seems to have cleared the problem
