### ISSUE TITLE
Intellisense does not work with Folder in WSL 2 filesystem opened over local network

### ISSUE THREAD

**Issue by f00f** [tailwindlabs/tailwindcss-intellisense#411]
I have a gatsby project in my WSL 2 home in the linux file system, i.e. in `/home/f00f/my-project/`.
For editing in VS Code I go to `\\wsl$\Ubuntu-20.04\home\f00f\my-project\` in Windows Explorer and then select "Open in VS Code" in the context menu.

So code lives in linux fs, VS Code runs in Windows, linux fs is shared via network (which is a default WSL 2 feature, not configured by me).

When I enable the extension I get the following error message:

```
[Error - 16:59:26] Tailwind CSS: ENOENT: no such file or directory, open '\wsl$\Ubuntu-20.04\home\f00f\my-project\tailwind.config.js'
```

which is almost the correct path. Discovery finds the config file, but `normalize-path` in `server.ts : init()` changes the actual path and removes the first backslash. That changes the path from a network path to an absolute path on the current drive on Windows.

Note: in a [previous comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/398#issuecomment-920099348) I wrote the path in the error message with forward slashes. I cannot reproduce whether it really had forward slashes at that time. Right now I see backslashes.

**Comment by f00f** [comment]
@SupunSam has the same error, see here: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/398#issuecomment-921889061

**Comment by guilherme-marin** [comment]
Same environment(WSL2, Ubuntu/windows 11) and error here. Here is the full output: 

`[Error - 14:28:59] Tailwind CSS: ENOENT: no such file or directory, open '\wsl$\Ubuntu\home\tainazao\projetos\lojista-next-site\tailwind.config.js'
Error: ENOENT: no such file or directory, open '\wsl$\Ubuntu\home\tainazao\projetos\lojista-next-site\tailwind.config.js'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at Dn (c:\Users\Guilherme Marin\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.0\dist\server\tailwindServer.js:56:348295)
    at c:\Users\Guilherme Marin\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.0\dist\server\tailwindServer.js:56:348035
    at Nn (c:\Users\Guilherme Marin\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.0\dist\server\tailwindServer.js:56:348228)
    at c:\Users\Guilherme Marin\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.0\dist\server\tailwindServer.js:56:352952
    at Generator.next (<anonymous>)
    at o (c:\Users\Guilherme Marin\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.0\dist\server\tailwindServer.js:56:348527)`


@f00f, Have you found any work around about this error?
