### ISSUE TITLE
TypeError: sequence item 8: expected str instance, NoneType found

### ISSUE THREAD

**Issue by zigi05** [tailwindlabs/tailwindcss-intellisense#427]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.0

**What version of Tailwind CSS are you using?**

v2.2.9

**What package manager are you using?**

npm

**What operating system are you using?**

Windows 10

**Reproduction URL**

https://github.com/sublimelsp/LSP-tailwindcss/issues/21

**Describe your issue**

The issue seems to be with tailwind-intellisense when using LSP-Tailwindcss in Sublime Text 4 on Windows 10.

_More details of the issue can be found [here](https://github.com/sublimelsp/LSP-tailwindcss/issues/21)._

It works well in [tailwind-example](https://github.com/ParamagicDev/tailwind-example) on my local machine, but it doesn't work in my project. The tailwind-example uses _tailwindcss@1.1.2_ and my project uses  _tailwindcss@2.2.9_. Once I update tailwindcss to version 2.2.9 in tailwind-example, it stops working as well and I get the same error as in my project, so it seems not to be working with tailwindcss version at least 2.2+:

```
Traceback (most recent call last):
  File "C:\Users\zigi\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 175, in on_capability_added_async
  File "C:\Users\zigi\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 96, in _register_auto_complete_triggers
  File "C:\Users\zigi\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 130, in _apply_auto_complete_triggers
TypeError: sequence item 8: expected str instance, NoneType found
```

**Comment by predragnikolic** [comment]
Thanks for opening the issue here!

Are you sure you are using version 0.7.0? 

I think that you are using version 0.6.15. (that is the latest released version of LSP-tailwindcss https://github.com/sublimelsp/LSP-tailwindcss/releases)

**Comment by bradlc** [comment]
Hey @zigi05. It sounds like this was already fixed in `LSP-tailwindcss`, but I also made a small change to ensure that we don't try to register an `undefined` (`None` in Python) trigger character, just in case 👍
