### ISSUE TITLE
Got a bug with the tailwindcss@3.0.0-alpha.1 version

### ISSUE THREAD

**Issue by MatteoGauthier** [tailwindlabs/tailwindcss-intellisense#435]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.1

**What version of Tailwind CSS are you using?**

3.0.0-alpha.1

**What package manager are you using?**

yarn

**What operating system are you using?**

Windows

**Reproduction URL**

https://github.com/MatteoGauthier/tw-bug-forms

**Describe your issue**

With the @tailwindcss/forms plugin an issue appear with the beta version of tailwindcss

```
[Error - 00:21:33] Tailwind CSS: Cannot read property '500' of undefined
TypeError: Cannot read property '500' of undefined
    at d:\Dev\WebDev\TailwindCSS\tw-bug-forms\node_modules\@tailwindcss\forms\src\index.js:34:63
    at registerPlugins (d:\Dev\WebDev\TailwindCSS\tw-bug-forms\node_modules\tailwindcss\lib\lib\setupContextUtils.js:591:61)
    at createContext (d:\Dev\WebDev\TailwindCSS\tw-bug-forms\node_modules\tailwindcss\lib\lib\setupContextUtils.js:732:5)
    at Object.module (c:\Users\mgpro\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.1\dist\server\tailwindServer.js:56:354881)
    at c:\Users\mgpro\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.1\dist\server\tailwindServer.js:56:358487
    at Generator.next (<anonymous>)
    at c:\Users\mgpro\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.1\dist\server\tailwindServer.js:56:349117
    at new Promise (<anonymous>)
    at Fn (c:\Users\mgpro\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.1\dist\server\tailwindServer.js:56:348862)
    at c:\Users\mgpro\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.1\dist\server\tailwindServer.js:56:357090
```

**Comment by bradlc** [comment]
Hey @MatteoGauthier. I can't tell from your repo (did you forget to push some changes?) but it sounds like you are using a version of `@tailwindcss/forms` that is not compatible with `tailwindcss` v3. You need to use the `next` version (currently `0.4.0-alpha.1`):

```
yarn add @tailwindcss/forms@next
```

Can you confirm that this fixes your issue?
