### ISSUE TITLE
Nothing works with 0.7.6, but 0.7.5 is ok

### ISSUE THREAD

**Issue by vladdu** [tailwindlabs/tailwindcss-intellisense#468]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.6

**What version of Tailwind CSS are you using?**

v3.0.15

**What package manager are you using?**

npm
node 16.13.2

**What operating system are you using?**

Ubuntu Linux

**Reproduction URL**

I get this problem on all my projects. Just a freshly installed and initialized tailwindcss is enough.

**Describe your issue**

Things don't work (completion, color swatch). These work fine with 0.7.5. No error is reported except as below.

The error below is shown in the terminal, but 0.7.5 does that too, so maybe it's not a problem.

```
[Error - 10:13:37 PM] Tailwind CSS: Expected a non-empty string
TypeError: Expected a non-empty string
    at Function.l.makeRe (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:46:25662)
    at Function.l.makeRe (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:39:14765)
    at y (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:2:116977)
    at /home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:2:117894
    at Array.map (<anonymous>)
    at Object.t.convertPatternsToRe (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:2:117887)
    at t.default._getNegativePatternsRe (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:2:104034)
    at t.default.getFilter (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:2:103797)
    at o._getReaderOptions (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:2:108222)
    at o.read (/home/vlad/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.6/dist/server/tailwindServer.js:2:103302)
```

**Comment by bradlc** [comment]
Hey @vladdu. Could you share your VS Code settings please?

**Comment by vladdu** [comment]
Sure. I have a lot of things in the settings, though, so I trimmed down parts that are not important.

```
{
    "workbench.startupEditor": "newUntitledFile",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "files.autoSave": "afterDelay",
    "explorer.confirmDragAndDrop": false,
    "workbench.iconTheme": "eq-material-theme-icons-darker",
    "workbench.colorTheme": "One Dark Pro",
    "editor.fontSize": 11,
    "git.autofetch": true,
    "vsonline.authentication.accountProvider": "Microsoft",
    "vsonline.accountProvider": "Microsoft",
    "editor.fontFamily": "'Cascadia Code PL',Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "terminal.integrated.fontSize": 12,
    "headwind.defaultSortOrder": [
        "container",
		.....
        "clear-left"
    ],
    "files.trimFinalNewlines": true,
    "vsonline.enableSuspendOnIdleConnection": false,
    "editor.renderWhitespace": "boundary",
    "headwind.prependCustomClasses": true,
    "headwind.runOnSave": false,
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "liveServer.settings.donotShowInfoMsg": true,
    "liveServer.settings.donotVerifyTags": true,
    "vscodeGoogleTranslate.preferredLanguage": "sv",
    "codespaces.accountProvider": "Microsoft",
    "codespaces.enableSuspendOnIdleConnection": false,
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.wordWrap": "on",
    "python.languageServer": "Pylance",
    "[javascript]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter.notebook.ipynb"
    },
    "python.showStartPage": false,
    "[jsonc]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "redhat.telemetry.enabled": false,
    "files.exclude": {
        "": true,
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "solidity.compileUsingRemoteVersion": "v0.5.0+commit.1d4f565a",
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.diagnosticMode": "workspace",
    "python.analysis.indexing": true,
    "editor.formatOnPaste": true,
    "html.format.endWithNewline": true,
    "html.format.indentHandlebars": true,
    "html.format.templating": true,
    "files.trimTrailingWhitespace": true,
    "svelte.enable-ts-plugin": true,
    "security.workspace.trust.untrustedFiles": "open",
    "python.formatting.provider": "black",
    "python.linting.mypyEnabled": true,
    "python.linting.pylintEnabled": true,
    "python.defaultInterpreterPath": "python3",
    "python.linting.ignorePatterns": [
        "**/site-packages/**/*.py",
        ".vscode/*.py",
        ".eggs/**/*.*"
    ],
    "tailwindCSS.emmetCompletions": true
}
```

**Comment by bradlc** [comment]
@vladdu Can you remove this line and see if that fixes the issue? You might need to reload the window afterwards (`Developer: Reload Window` command):

```diff
  "files.exclude": {
-     "": true,
      "**/.classpath": true,
      "**/.project": true,
      "**/.settings": true,
      "**/.factorypath": true
  },
```

**Comment by vladdu** [comment]
No, doesn't help.

**Comment by bradlc** [comment]
> No, doesn't help. But removing all settings seems toi help, so I will try to find out which one is the issue.

Is your tailwind config file in one of these folders?

```
**/.classpath
**/.project
**/.settings
**/.factorypath
```

If it is then that would explain it. The extension now takes `files.exclude` into account, and won't activate if your config file is excluded.

**Comment by vladdu** [comment]
Ha, weird: I put back my previous settings, and now it works... Thanks for looking at this, I'll get back if I can see it again.
