### ISSUE TITLE
SyntaxError: package.json (directory description file): SyntaxError: Unexpected token } in JSON

### ISSUE THREAD

**Issue by maltoze** [tailwindlabs/tailwindcss-intellisense#497]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.7

**What version of Tailwind CSS are you using?**

v3.0.7

**What package manager are you using?**

yarn

**What operating system are you using?**

Windows(using remote-ssh)

**Reproduction URL**

**Describe your issue**

When i edit `package.json` file will raise this error.

```
Failed to load workspace modules.
Using bundled version of `tailwindcss`: v3.0.11
Using bundled version of `postcss`: v8.3.9
[Error - 2:38:25 PM] Tailwind CSS: package.json (directory description file): SyntaxError: Unexpected token } in JSON at position 549
SyntaxError: package.json (directory description file): SyntaxError: Unexpected token } in JSON at position 549
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:62066)
    at a.provideSync (/home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:59056)
    at e.exports.r.readJson (/home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:89685)
    at /home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:64882
    at i (/home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:91335)
    at e.exports (/home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:91442)
    at l (/home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:64644)
    at Object.t.loadDescriptionFile (/home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:65450)
    at /home/admin/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:63786
```
Is it because I'm using workspace?

```
// package.json
{
  "name": "foo",
  "version": "1.0.0",
  "repository": "",
  "author": "",
  "license": "MIT",
  "private": true,
  "workspaces": [
    "workspace-a",
    "workspace-b"
  ],
  "scripts": {
    "lint": "eslint . --ext .ts,.js",    // error will be raised here
  },
  "devDependencies": {
    "eslint": "^8.9.0",
    "typescript": "^4.5.5"
  }
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue is that you have a trailing comma (`,`) on that line which is not allowed. If you remove it, then everything should work as expected!
```diff
{
  "name": "foo",
  "version": "1.0.0",
  "repository": "",
  "author": "",
  "license": "MIT",
  "private": true,
  "workspaces": [
    "workspace-a",
    "workspace-b"
  ],
  "scripts": {
-   "lint": "eslint . --ext .ts,.js",
+   "lint": "eslint . --ext .ts,.js"
  },
  "devDependencies": {
    "eslint": "^8.9.0",
    "typescript": "^4.5.5"
  }
}
```

**Comment by maltoze** [comment]
@RobinMalfait yes, I know...
but how to disable this?
![image](https://user-images.githubusercontent.com/18044730/156101871-f5535e60-5a0c-455c-9233-5568fd77f9d2.png)
