### ISSUE TITLE
Error: Can't resolve '../util/log'...

### ISSUE THREAD

**Issue by bwklein** [tailwindlabs/tailwindcss-intellisense#504]
**What version of Tailwind CSS IntelliSense are you using?**

v0.7.7

**What version of Tailwind CSS are you using?**

For example: v3.0.23

**What package manager are you using?**

npm

**What operating system are you using?**

Ubuntu

**Describe your issue**

```
Failed to load workspace modules.
Using bundled version of `tailwindcss`: v3.0.11
Using bundled version of `postcss`: v8.3.9
[Error - 11:19:59 PM] Tailwind CSS: Can't resolve '../util/log' in '/workspace/thundertheme/node_modules/tailwindcss/lib/public'
Error: Can't resolve '../util/log' in '/workspace/thundertheme/node_modules/tailwindcss/lib/public'
    at l (/workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:77251)
    at /workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:77938
    at /workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:78502
    at eval (eval at create (/workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:50:275635), <anonymous>:15:1)
    at /workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:78502
    at eval (eval at create (/workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:50:275635), <anonymous>:27:1)
    at /workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:64324
    at /workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:78502
    at eval (eval at create (/workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:50:275635), <anonymous>:15:1)
    at /workspace/.vscode-remote/extensions/bradlc.vscode-tailwindcss-0.7.7/dist/server/tailwindServer.js:2:78502
Found Tailwind CSS config file: /workspace/thundertheme/tailwind.config.cjs
Loaded postcss v8.4.7: /workspace/thundertheme/node_modules/postcss
Loaded tailwindcss v3.0.23: /workspace/thundertheme/node_modules/tailwindcss

warn - The RTL features in Tailwind CSS are currently in preview.
warn - Preview features are not covered by semver, and may be improved in breaking ways at any time.
```

**Comment by bradlc** [comment]
Hey @bwklein. Please can you share a GitHub repository of a project where you are seeing this error? Unfortunately without a reproduction it is not going to be possible to debug that issue. Thank you!

**Comment by bwklein** [comment]
The project is 'private' but not really a secret.  I have attached a zip of the entire project repo here.
I can also spin up a GitPod session with this project and show you what I am seeing.

[thundertheme-main (1).zip](https://github.com/tailwindlabs/tailwindcss-intellisense/files/8483656/thundertheme-main.1.zip)

**Comment by bradlc** [comment]
I'm going to close this because a reproduction was not provided, as requested in the new issue template. Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but without a reproduction it isn't going to be possible to track down the source of the problem. If you're still seeing this please open a new issue and include a link to a GitHub repository that we can clone to immediately see the issue. Thank you! 🙏

**Comment by bwklein** [comment]
@bradlc I apologize for not responding, I tried to make a secondary GitHub repo for the project to demonstrate the issue and could not repeat it in the clone of the project.  I don't know the cause yet, but since it is difficult and inconsistent to reproduce I am fine with this being closed for now.  If I can find a good way to reproduce it I will do as you suggest.
