### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by sunscreem** [tailwindlabs/tailwindcss-intellisense#530]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.1

**What version of Tailwind CSS are you using?**

N/A

**What package manager are you using?**

N/A

**What operating system are you using?**

Linux

**Describe your issue**

When switching between projects that do *not* have tailwind installed I get a toast message about `require(...) is not a function` in VS Code.

The output shows this:

```
Using bundled version of `tailwindcss`: v3.0.11
Using bundled version of `postcss`: v8.3.9
[Error - 6:39:48 PM] Tailwind CSS: require(...) is not a function
TypeError: require(...) is not a function
    at Object.<anonymous> (/home/forge/lc.sunscreem.xyz/vendor/craftcms/cms/src/web/assets/pluginstore/tailwind.config.js:27:57)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Xd._require.Vi.default.require (/home/forge/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.8.1/dist/tailwindServer.js:179:63908)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/forge/.vscode-server/extensions/bradlc.vscode-tailwindcss-0.8.1/dist/tailwindServer.js:690:10498
    at Generator.next (<anonymous>)
```

Is there a way to say to the plug in "ignore this site if it's not got a tailwind config"?

**Comment by bradlc** [comment]
Hey @sunscreem 

> _Is there a way to say to the plug in "ignore this site if it's not got a tailwind config"?_

It looks like the extension is activating because there _is_ a Tailwind config file in the workspace (`vendor/craftcms/cms/src/web/assets/pluginstore/tailwind.config.js`).

If you don't want it to activate you can either:

1. Disable the extension completely for that workspace
2. Add the `vendor` folder to the `tailwindCSS.files.exclude` configuration option:
    ```diff
      "tailwindCSS.files.exclude": [
        "**/.git/**",
        "**/node_modules/**",
        "**/.hg/**",
    +   "**/vendor/**"
      ]
    ```

I hope that helps!

**Comment by sunscreem** [comment]
@bradlc PERFECT! Thank you - I wished I'd spotted that config file earlier :)
