### ISSUE TITLE
Extension crashing

### ISSUE THREAD

**Issue by JoelDesante** [tailwindlabs/tailwindcss-intellisense#547]
**What version of Tailwind CSS IntelliSense are you using?**
v0.8.3

**What version of Tailwind CSS are you using?**
v3.0.24

**What package manager are you using?**
npm

**What operating system are you using?**
macOS

**Describe your issue**
```
Found Tailwind CSS config file: /Users/joeldesante/Development/Rate-a-loo/tailwind.config.js
Loaded postcss v8.4.13: /Users/joeldesante/Development/Rate-a-loo/node_modules/postcss
Loaded tailwindcss v3.0.24: /Users/joeldesante/Development/Rate-a-loo/node_modules/tailwindcss
[Error - 11:36:03 PM] Unhandled exception: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at /Users/joeldesante/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:692:9122
    at Array.flatMap (<anonymous>)
    at Bj.updateCapabilities (/Users/joeldesante/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:692:9090)
    at /Users/joeldesante/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:692:8080
    at L (/Users/joeldesante/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:690:3439)
    at Object.<anonymous> (/Users/joeldesante/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:690:3511)
    at Generator.throw (<anonymous>)
    at s (/Users/joeldesante/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:1:1103)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

tailwind.config.js
```
module.exports = {
  content: ["./public/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

The extension will not work due to it crashing. I am unsure of what this error message is telling me to do.

**Comment by JoelDesante** [comment]
Okay I found the solution for my issue.

I needed to first change my tailwind config file to use the extension `cjs`. 
It should look like this `tailwind.confg.cjs`

My project is setup to use ESM (`import/export`) rather than CommonJS (`require`) syntax so that appears to have been my issue.

**Comment by stijnwesterhof** [comment]
I'm having the same issue, but this didn't fix it for me :(
