### ISSUE TITLE
Requiring 3rd party packages in Tailwind config breaks extension when using yarn PnP

### ISSUE THREAD

**Issue by renet** [tailwindlabs/tailwindcss-intellisense#548]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.3

**What version of Tailwind CSS are you using?**

v3.0.23

**What package manager are you using?**

yarn v3

**What operating system are you using?**

macOS with Apple Silicon

**Reproduction URL**

https://github.com/renet/tailwind-intellisense-repro

**Describe your issue**

When using yarn PnP and a `tailwind.config.js` that requires additional packages, I used to get the following message in VS Code:

> Failed to initialise: Error: Your application tried to access @emdgroup-liquid/liquid, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
> 
> <callstack>

Sorrily I can't reproduce this any longer, so I can't send you the call stack, but rather copied this message from another issue here. But the call stack ended at the file `.pnp.cjs`, if I remember correctly.

After fiddling around a little and trying to create a repro repo, I do no longer get this message (not even in my actual project that the error initially occurred in), but I get a different message now, when I look into the Ouput Tab of Tailwind CSS IntelliSense:

```
[Error - 1:02:03 PM] Unhandled exception: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at /Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:692:9122
    at Array.flatMap (<anonymous>)
    at Bj.updateCapabilities (/Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:692:9090)
    at /Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:692:8080
    at L (/Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:690:3439)
    at Object.<anonymous> (/Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:690:3511)
    at Generator.throw (<anonymous>)
    at s (/Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.3/dist/tailwindServer.js:1:1103)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I don't know what I've changed so that the former message is no longer displayed. Nevertheless, the result is the same: The Tailwind CSS IntelliSense extension is not working, while the actual Tailwind CSS config seems to work properly in the project.

You can fix the repro repo, if you remove the lines 1 and 6 in the [tailwind.config.js](https://github.com/renet/tailwind-intellisense-repro/blob/main/tailwind.config.js). IntelliSense auto-completion can then be tested in the `test.html` file in the project root.

**Comment by bradlc** [comment]
Hey @renet. Thanks for reporting. The `map` error should be fixed in `v0.8.4` 👍

**Comment by renet** [comment]
Thank you! This now results in / leads me back to the original bug then I actually tried to reproduce. The above mentioned repro repo now again produces the following output on startup:

```
Found Tailwind CSS config file: /Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js
Failed to load workspace modules.
Using bundled version of `tailwindcss`: v3.0.11
Using bundled version of `postcss`: v8.3.9
[Error - 12:22:48 PM] Tailwind CSS: Your application tried to access @emdgroup-liquid/liquid, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @emdgroup-liquid/liquid (via "@emdgroup-liquid/liquid/dist/css/tailwind-preset.js")
Required by: /Users/M305642/dev/prv/tailwind-intellisense-repro/

Require stack:
- /Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js
- /Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.4/dist/tailwindServer.js
Error: Your application tried to access @emdgroup-liquid/liquid, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @emdgroup-liquid/liquid (via "@emdgroup-liquid/liquid/dist/css/tailwind-preset.js")
Required by: /Users/M305642/dev/prv/tailwind-intellisense-repro/

Require stack:
- /Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js
- /Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.4/dist/tailwindServer.js
    at Function.require$$0.Module._resolveFilename (/Users/M305642/dev/prv/tailwind-intellisense-repro/.pnp.cjs:10108:13)
    at Module.Vd._require.Gi.default.require (/Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.4/dist/tailwindServer.js:179:63791)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Object.require$$0.Module._extensions..js (/Users/M305642/dev/prv/tailwind-intellisense-repro/.pnp.cjs:10152:33)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Function.require$$0.Module._load (/Users/M305642/dev/prv/tailwind-intellisense-repro/.pnp.cjs:9992:14)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
```

Can you please re-open the ticket? It would be great, if you looked into this issue, again! Thanks! :)

**Comment by renet** [comment]
@bradlc Please re-review (see above).
