### ISSUE TITLE
this in windows tailwindcss-intellisense is Error

### ISSUE THREAD

**Issue by jipika** [tailwindlabs/tailwindcss-intellisense#550]
Found Tailwind CSS config file: e:\t\tailwind.config.js
Loaded postcss v8.4.13: e:\t\node_modules\tailwindcss\node_modules\postcss
Loaded tailwindcss v3.0.24: e:\t\node_modules\tailwindcss
[Error - 14:12:29] Unhandled exception: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at c:\Users\Administrator\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.3\dist\tailwindServer.js:692:9122
    at Array.flatMap (<anonymous>)
    at Bj.updateCapabilities (c:\Users\Administrator\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.3\dist\tailwindServer.js:692:9090)
    at c:\Users\Administrator\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.3\dist\tailwindServer.js:692:8080
    at L (c:\Users\Administrator\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.3\dist\tailwindServer.js:690:3439)
    at Object.<anonymous> (c:\Users\Administrator\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.3\dist\tailwindServer.js:690:3511)
    at Generator.throw (<anonymous>)
    at s (c:\Users\Administrator\.vscode\extensions\bradlc.vscode-tailwindcss-0.8.3\dist\tailwindServer.js:1:1103)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ChenKuo** [comment]
I had the same issue when using the ES6 `export default` syntax instead of the CommonJS `module.exports` syntax in tailwind.config.js . Since my build tool does not support CommonJS, I worked around the issue by copying tailwind.config.js into tailwind.config.cjs, but change `export default` to `module.exports =` (also added the cjs to .gitignore).

**Comment by bradlc** [comment]
Thanks for reporting. This error should be fixed in `v0.8.4` 👍

**Comment by jipika** [comment]
I solved the problem because the nodeJS version is too low. After the upgrade, I upgraded sass and solved the problem
