### ISSUE TITLE
Requiring 3rd party packages in Tailwind config breaks extension when using yarn PnP

### ISSUE THREAD

**Issue by renet** [tailwindlabs/tailwindcss-intellisense#567]
What version of Tailwind CSS IntelliSense are you using?

v0.8.6

What version of Tailwind CSS are you using?

v3.0.23

What package manager are you using?

yarn v3

What operating system are you using?

macOS with Apple Silicon

Reproduction URL

https://github.com/renet/tailwind-intellisense-repro

Describe your issue

When using yarn PnP and a tailwind.config.js that requires additional packages, I get the following message in VS Code:

```
Found Tailwind CSS config file: /Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js
Failed to load workspace modules.
Using bundled version of `tailwindcss`: v3.0.11
Using bundled version of `postcss`: v8.3.9
[Error - 10:59:31 AM] Tailwind CSS: Your application tried to access @emdgroup-liquid/liquid, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @emdgroup-liquid/liquid (via "@emdgroup-liquid/liquid/dist/css/tailwind-preset.js")
Required by: /Users/M305642/dev/prv/tailwind-intellisense-repro/

Require stack:
- /Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js
- /Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js
Error: Your application tried to access @emdgroup-liquid/liquid, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @emdgroup-liquid/liquid (via "@emdgroup-liquid/liquid/dist/css/tailwind-preset.js")
Required by: /Users/M305642/dev/prv/tailwind-intellisense-repro/

Require stack:
- /Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js
- /Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js
    at Function.require$$0.Module._resolveFilename (/Users/M305642/dev/prv/tailwind-intellisense-repro/.pnp.cjs:10108:13)
    at Module.Vd._require.Gi.default.require (/Users/M305642/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:179:63791)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/M305642/dev/prv/tailwind-intellisense-repro/tailwind.config.js:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Object.require$$0.Module._extensions..js (/Users/M305642/dev/prv/tailwind-intellisense-repro/.pnp.cjs:10152:33)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Function.require$$0.Module._load (/Users/M305642/dev/prv/tailwind-intellisense-repro/.pnp.cjs:9992:14)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
```

You can fix the repro repo, if you remove the lines 1 and 6 in the [tailwind.config.js](https://github.com/renet/tailwind-intellisense-repro/blob/main/tailwind.config.js). IntelliSense auto-completion can then be tested in the test.html file in the project root.

This was reported in https://github.com/tailwindlabs/tailwindcss-intellisense/issues/548, as well, but got closed because there was a preceding big that has then been fixed. But the initial bug still exists.

**Comment by bradlc** [comment]
Hey @renet. I can't reproduce this. Please can you share your VS Code settings in JSON format, and a list of the VS Code extensions you have installed (`code --list-extensions --show-versions`)?

**Comment by renet** [comment]
```js
// settings.json
{
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "files.autoSave": "onFocusChange",
  "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  "eslint.format.enable": true,
  "git.openDiffOnClick": false,
  "git.enableSmartCommit": true,
  "git.confirmSync": false,
  "git.autofetch": true,
  "explorer.confirmDelete": false,
  "git.allowForcePush": true,
  "files.associations": {
    "*.css": "postcss"
  },
  "git.confirmForcePush": false,
  "editor.wordWrap": "on",
  "postcss.validate": false,
  "typescript.format.enable": false,
  "javascript.format.enable": false,
  "editor.formatOnSave": true,
  "[sass]": {
    "editor.defaultFormatter": "syler.sass-indented"
  },
  "explorer.confirmDragAndDrop": false,
  "[postcss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "terminal.external.osxExec": "iTerm.app",
  "git-graph.repository.sign.commits": true,
  "git-graph.repository.sign.tags": true,
  "git-graph.repository.commits.showSignatureStatus": true,
  "git.enableCommitSigning": true,
  "git.autoStash": true,
  "git.useCommitInputAsStashMessage": true,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "window.zoomLevel": 1
}
```

```sh
# code --list-extensions --show-versions
arcanis.vscode-zipfs@3.0.0
bradlc.vscode-tailwindcss@0.8.6
dbaeumer.vscode-eslint@2.2.2
eamodio.gitlens@12.1.1
esbenp.prettier-vscode@9.5.0
heybourn.headwind@1.7.0
mhmadhamster.postcss-language@2.1.0
mhutchie.git-graph@1.30.0
ms-vsliveshare.vsliveshare@1.0.5625
stylelint.vscode-stylelint@1.2.2
syler.sass-indented@1.8.21
vunguyentuan.vscode-css-variables@2.3.8
vunguyentuan.vscode-postcss@0.2.0
```

VS Code Version: 1.68.1

Thanks for your help!

**Comment by bradlc** [comment]
Thanks for sharing. How are you opening the folder in VS Code? Are you just opening it in its own window?

**Comment by ardasevinc** [comment]
I think I got something. Here is the steps I took to produce differing behaviors which might be able to shine light on this.

**Comment by ardasevinc** [comment]
I had the exact same issue with a different tailwindcss plugin.
x86 arch linux device with vs code `v1.68.1` 
My versions are:
  - tailwindcss 3.1.6
  - yarn 3.2.1
 
I believe I have something which can help fix this. Here are the steps I took to obtain an interesting behavior:

1. Scaffolded a vite + react + tailwindcss + daisyui (tailwindcss plugin) project. The repo and the ingredients to create it can be found [here](https://github.com/ardasevinc/tailwindcss-yarn-intellisense)
2. Successfully reproduced the issue, or so I thought.
3. Pushed the reproduction project to github. 
4. Cloned the repo in a new folder as a test and ran `yarn`. 
5. Now I could not reproduce the issue, everything worked.

I have repeated the steps above (clone + `$ yarn`) with @renet 's repro repo and again, I encountered the error in the first clone and no error in the second. It seems that the error can only be reproduced if yarn doesn't have pkg in the cache or however it saves the pnp installs. This might also be the reason why @bradlc wasn't able to reproduce the issue. Hope it helps!

**Comment by renet** [comment]
@ardasevinc Thanks for your help. Sorrily I was not able to reproduce this behavior on my machine. As soon as I open the package.json in a newly cloned project folder in VS code, I get the error I mentioned above. No matter how many times I ran `yarn` in this or the previous project clones.

@bradlc Can I somehow help you further with this? The only think I can possibly think of is that for some reason you try to install the dependencies using yarn v1 instead of v3, but I just tried this by explicitly setting the yarn version before running `yarn`, and even then I get the error.

**Comment by ardasevinc** [comment]
> @ardasevinc Thanks for your help. Sorrily I was not able to reproduce this behavior on my machine. As soon as I open the package.json in a newly cloned project folder in VS code, I get the error I mentioned above. No matter how many times I ran `yarn` in this or the previous project clones.

Right. No problem. This issue is finicky to reproduce. Can you try to scaffold a project *from scratch*, then install that `@emdgroup-liquid` package and then clone the repro code, run  yarn and see if it goes away? In my findings it was not possible to reproduce the issue if you scaffold the project, install the offending plugin and clone the repro repo again. I agree that this is convoluted but I just tested this behavior on my machine.

**Comment by renet** [comment]
Right now I'm using Node v16.17.0 (installed using nvm) and as specified in the project, I use yarn 3.2.0 (default yarn version, if not specified in the project, is 1.22.15). I initially installed yarn using corepack, following the instructions [here](https://yarnpkg.com/getting-started/install). I used a little earlier version of Node (something >= 16.10, though) when I initially installed yarn on my machine.

The above mentioned version information was retrieved using the zsh terminal inside VS Code. I used iTerm 2 as terminal to  install nvm, node and yarn in the first place. Hope this helps.

**Comment by norbertsongin** [comment]
I'm getting the same issue with [@headlessui/tailwindcss](https://www.npmjs.com/package/@headlessui/tailwindcss)

```
[Error - 5:24:05 PM] Tailwind CSS: Can't resolve '@headlessui/tailwindcss' in '/Users/user/Projects/XYZ/frontend'
Error: Can't resolve '@headlessui/tailwindcss' in '/Users/user/Projects/XYZ/frontend'
    at f (/Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:130:7129)
    at /Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:131:713
    at /Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:5:78), <anonymous>:27:1)
    at /Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:134:7650
    at /Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:134:401
    at eval (eval at create (/Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /Users/user/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:134:401

```

**Comment by renet** [comment]
@bradlc Any update on this one? Is there anything I can do to help you with this? Would be open to a peer session, if that helps.

**Comment by nimish-kumar** [comment]
This is happening on npm as well. It is unable to resolve paths. 

My `tailwind.config.js` is as below:
```
const { fadeNavy, darkNavy } = require("./assets");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{tsx, ts}"],
  theme: {
    extend: {
      colors: {
        "fade-navy": fadeNavy,
        "dark-navy": darkNavy,
      },
    },
  },
  plugins: [],
};
```
Extension console error:

```
[tailwind.config.js] Loaded tailwindcss v3.2.4: /home/nimish/Documents/MyProject/node_modules/tailwindcss
[tailwind.config.js] Building...
[Error - 5:51:53 PM] Tailwind CSS: Can't resolve './assets' in '/home/nimish/Documents/bookmyshow-clone'
Error: Can't resolve './assets' in '/home/nimish/Documents/bookmyshow-clone'
    at h (/home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:130:7129)
    at /home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:131:713
    at /home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:134:401
    at eval (eval at create (/home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:134:401
    at eval (eval at create (/home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:5:78), <anonymous>:27:1)
    at /home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:134:7650
    at /home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:134:401
    at eval (eval at create (/home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:5:78), <anonymous>:15:1)
    at /home/nimish/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.5/dist/tailwindServer.js:134:401
```

**Comment by rokoroku** [comment]
Hi! I'd like to share my workaround here.

```javascript
try {
  require('./.pnp.cjs').setup();
} catch {
  // ignore
}
```
add manual pnp setup code to the top-level tailwind.config.js file, then it works. 

This problem seems to be the code below is not functioning properly.

https://github.com/tailwindlabs/tailwindcss-intellisense/blob/8e70fbb46073b7e46c6c11c72867e755c9ad1cd0/packages/tailwindcss-language-server/src/server.ts#L576-L597

FYI. in my case, I am using a VSCode workspace.

**Comment by renet** [comment]
@rokoroku Thanks for posting this workaround, but I'm afraid this doesn't fix the problem in the repro repo (in my case).

**Comment by alistairstead** [comment]
I can confirm I have the same issue using neovim and tailwindcss LSP. The problem manifests only when I use an import to a workspace package that includes shared preset config

**Comment by ardasevinc** [comment]
I suggest everyone here to stop using yarn v3. I've had loads of issues with it and learned that the industry does not use yarn v3 and does not bug-check/test their libraries on it. Use yarn classic... or pnpm but you might still have similar issues (I did)

Let's talk again when everyone wants to use yarnV3 or pnpm
