### ISSUE TITLE
Can't resolve 'node:path'

### ISSUE THREAD

**Issue by JounQin** [tailwindlabs/tailwindcss-intellisense#584]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.6

**What version of Tailwind CSS are you using?**

v3.1.6

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Reproduction URL**

N/A, it is thrown in VSCode

**Describe your issue**

```js
// tailwind.config.js
const path = require('node:path');

const { createGlobPatternsForDependencies } = require('@nrwl/angular/tailwind');

const sharedTailwindConfig = require('../../libs/tailwind-preset/tailwind.config');

module.exports = {
  presets: [sharedTailwindConfig],
  content: [
    path.join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
};
```

```log
[Error - 11:02:57 PM] Tailwind CSS: Can't resolve 'node:path' in '/Users/JounQin/Workspaces/Alauda/alauda-fe/apps/crd-form-app'
Error: Can't resolve 'node:path' in '/Users/JounQin/Workspaces/Alauda/alauda-fe/apps/crd-form-app'
    at u (/Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:130:6972)
    at /Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:131:640
    at /Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
    at eval (eval at create (/Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:1:1), <anonymous>:15:1)
    at /Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
    at eval (eval at create (/Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:1:1), <anonymous>:27:1)
    at /Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:7259
    at /Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
    at eval (eval at create (/Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:1:1), <anonymous>:15:1)
    at /Users/JounQin/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.6/dist/tailwindServer.js:134:386
```

**Comment by JounQin** [comment]
When will this be released?
