### ISSUE TITLE
shows error when package.json has merge conflicts

### ISSUE THREAD

**Issue by diminutivesloop** [tailwindlabs/tailwindcss-intellisense#613]
**What version of Tailwind CSS IntelliSense are you using?**

v0.8.7

**What version of Tailwind CSS are you using?**

v3.1.8

**What package manager are you using?**

yarn

**What operating system are you using?**

macOS

**Reproduction URL**

**Describe your issue**

When resolving merge conflicts, if conflict markers appear in the project `package.json` file, then I get the following error:
```[Error - 10:29:23 AM] Tailwind CSS: package.json (directory description file): SyntaxError: Unexpected token < in JSON at position 4473
SyntaxError: package.json (directory description file): SyntaxError: Unexpected token < in JSON at position 4473
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:2:9273)
    at ax.provideSync (/Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:2:6268)
    at VJ.H.readJson (/Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:134:1845)
    at /Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:134:2367
    at i (/Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:134:2067)
    at bC.exports (/Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:134:2174)
    at s (/Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:134:2301)
    at Object.GJ [as loadDescriptionFile] (/Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:134:3122)
    at /Users/nathanielpalmer/.vscode/extensions/bradlc.vscode-tailwindcss-0.8.7/dist/tailwindServer.js:134:7075
```
Despite this error the extension appears to continue functioning as normal.

Since merge conflicts are a normal part of development this extension should be more resilient to parsing errors in `package.json` and shouldn't show an error in these cases.

**Comment by bradlc** [comment]
Since `v0.9.0` errors are no longer shown in the VS Code UI 👍
