### ISSUE TITLE
CSS Intellisense not working

### ISSUE THREAD

**Issue by wrench1815** [tailwindlabs/tailwindcss-intellisense#663]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

v3.2.4

**What package manager are you using?**

yarn

**What operating system are you using?**

Garuda Linux

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    extend: {},
    fontFamily: {
      sans: ['Mansalva', 'cursive'],
      serif: ['"Nanum Pen Script"', 'cursive'],
      mono: ['"Fira Code"', 'monospace'],
    },

// overide height
height: (theme) => ({
  auto: 'auto',
  ...theme('spacing'),
  '1/2': '50%',
  '1/3': '33.333333%',
  '2/3': '66.666667%',
  '1/4': '25%',
  '2/4': '50%',
  '3/4': '75%',
  '1/5': '20%',
  '2/5': '40%',
  '3/5': '60%',
  '4/5': '80%',
  '1/6': '16.666667%',
  '2/6': '33.333333%',
  '3/6': '50%',
  '4/6': '66.666667%',
  '5/6': '83.333333%',
  full: '100%',
  screen: 'calc(var(--vh) * 100)',
  min: 'min-content',
  max: 'max-content',
  fit: 'fit-content',
}),

// overide min-height
minHeight: {
  0: '0px',
  full: '100%',
  screen: 'calc(var(--vh) * 100)',
  min: 'min-content',
  max: 'max-content',
  fit: 'fit-content',
},

// overide max-height
maxHeight: (theme) => ({
  ...theme('spacing'),
  full: '100%',
  screen: 'calc(var(--vh) * 100)',
  min: 'min-content',
  max: 'max-content',
  fit: 'fit-content',
}),
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],

  // daisyUI config
  daisyui: {
    themes: ['pastel', 'dracula'],
    darkTheme: 'dracula',
  },
};

```

**VS Code settings**

```json
{
  "editor.fontFamily": "'FiraCode Nerd Font', 'Fira Code', 'Hack Nerd Font', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
  "editor.wordWrap": "on",
  "editor.accessibilitySupport": "off",
  "editor.definitionLinkOpensInPeek": true,
  "editor.linkedEditing": true,
  "editor.smoothScrolling": true,
  "editor.tabCompletion": "on",
  "editor.fontLigatures": true,
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "Shades of Purple",
  "editor.fontWeight": "500",
  "editor.formatOnPaste": true,
  "diffEditor.codeLens": true,
  // "editor.quickSuggestions": {
  //   "other": "on",
  //   "comments": "inline",
  //   "strings": "inline"
  // },
  "editor.quickSuggestions": {
    "comments": "on",
    "strings": "on",
    "other": "on"
  },
  "editor.quickSuggestionsDelay": 0,
  "editor.suggest.statusBar.visible": true,
  "files.autoGuessEncoding": true,
  "files.insertFinalNewline": true,
  "files.simpleDialog.enable": true,
  "workbench.editor.highlightModifiedTabs": true,
  "workbench.editor.limit.enabled": true,
  "workbench.editor.scrollToSwitchTabs": true,
  "window.titleSeparator": " | (╯°□°）╯︵ ┻━┻ | ",
  "explorer.incrementalNaming": "smart",
  "search.smartCase": true,
  "debug.inlineValues": "on",
  "extensions.autoCheckUpdates": false,
  "terminal.external.linuxExec": "konsole",
  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.cursorStyle": "line",
  "terminal.integrated.fontFamily": "'FiraCode Nerd Font',  'Fira Code', 'Hack Nerd Font', monospace",
  "terminal.integrated.fontWeight": "500",
  "editor.cursorBlinking": "expand",
  "editor.cursorSmoothCaretAnimation": true,
  "scm.inputFontFamily": "editor",
  "debug.console.fontFamily": "'FiraCode Nerd Font', 'Fira Code', 'Hack Nerd Font', monospace",
  "editor.suggestSelection": "recentlyUsedByPrefix",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "emmet.showSuggestionsAsSnippets": true,
  "git.allowForcePush": true,
  "git.alwaysShowStagedChangesResourceGroup": true,
  "git.autofetch": true,
  "git.enableCommitSigning": true,
  "gitlens.hovers.currentLine.over": "line",
  "gitlens.defaultDateFormat": "dddd - D MM, YYYY",
  "gitlens.defaultDateShortFormat": "D MMM, YYYY",
  "html.format.endWithNewline": true,
  "html.format.indentInnerHtml": true,
  "liveshare.audio.startCallOnShare": true,
  "merge-conflict.autoNavigateNextConflict.enabled": true,
  "path-intellisense.showHiddenFiles": true,
  "prettier.singleQuote": true,
  "python.globalModuleInstallation": true,
  "python.terminal.activateEnvInCurrentTerminal": true,
  "templates.Author": "Hardeep Kumar",
  "vsintellicode.features.python.deepLearning": "enabled",
  "liveshare.allowGuestDebugControl": true,
  "liveshare.allowGuestTaskControl": true,
  "liveshare.allowInvites": "all",
  "liveshare.guestApprovalRequired": true,
  "update.mode": "none",
  "extensions.autoUpdate": false,
  "python.pythonPath": "python3",
  "C_Cpp.clang_format_fallbackStyle": "{BasedOnStyle: LLVm, IndentWidth: 4, AlignAfterOpenBracket: Align, AlignConsecutiveAssignments: true, AlignConsecutiveMacros: true, AlignEscapedNewlines: Left, AlignTrailingComments: true, AllowShortBlocksOnASingleLine: false, AllowShortFunctionsOnASingleLine: Empty, AllowShortCaseLabelsOnASingleLine: false, ColumnLimit: 0, Cpp11BracedListStyle: false, PointerAlignment: Right, ReflowComments: true, SortIncludes: true, SpaceAfterCStyleCast: false, SpacesBeforeTrailingComments: 4, IndentCaseLabels: true }",
  "C_Cpp.default.cppStandard": "c++20",
  "C_Cpp.default.cStandard": "c17",
  "C_Cpp.default.intelliSenseMode": "gcc-x64",
  "C_Cpp.experimentalFeatures": "Enabled",
  "emmet.includeLanguages": {
    "jinja-html": "html",
    "django-html": "html"
  },
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.acceptSuggestionOnEnter": "off",
  "editor.suggest.insertMode": "replace",
  "workbench.editorAssociations": {
    "*.ico": "default",
    "*.ipynb": "jupyter-notebook"
  },
  "editor.formatOnType": true,
  "gitlens.advanced.telemetry.enabled": false,
  "sqltools.useNodeRuntime": true,
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "material-icon-theme.activeIconPack": "angular",
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "sonarlint.disableTelemetry": true,
  "python.linting.enabled": false,
  "editor.matchBrackets": "near",
  "C_Cpp.clang_format_sortIncludes": true,
  "python.languageServer": "Pylance",

  // django html specific settings
  "[django-html]": {
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "editor.formatOnSaveMode": "file"
  },

  // Django html association setup
  "files.associations": {
    "**/templates/**/*.html": "django-html",
    "**/templates/**/*": "django-txt",
    "**/requirements{/**,*}.{txt,in}": "pip-requirements",
    "**/*.html": "html"
  },

  // Jinja html association setup
  // "files.associations": {
  //   "**/templates/**/*.html": "jinja-html",
  //   "**/*.html": "jinja-html"
  // },
  "liveServer.settings.NoBrowser": true,
  "liveServer.settings.donotShowInfoMsg": true,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.suggest.showStatusBar": true,
  "C_Cpp.default.compilerPath": "/usr/bin/gcc",
  "better-comments.tags": [
    {
      // Important/Highlighted
      "tag": "!",
      "color": "#FF2D00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      // Info
      "tag": "?",
      "color": "#3498DB",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      // Depreciated
      "tag": "//",
      "color": "#e8e6e6",
      "strikethrough": true,
      "underline": false,
      "backgroundColor": "#de1d1d",
      "bold": false,
      "italic": false
      // 474747
    },
    {
      // Todo
      "tag": "todo",
      "color": "#FF8C00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      // Underline
      "tag": "*",
      "color": "#98C379",
      "strikethrough": false,
      "underline": true,
      "backgroundColor": "transparent",
      "bold": true,
      "italic": false
    },
    {
      // Param
      "tag": "@param",
      "color": "#1B98F5",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": true
    }
  ],
  "githubPullRequests.fileListLayout": "flat",
  "window.dialogStyle": "custom",
  "diffEditor.ignoreTrimWhitespace": false,
  "git.confirmSync": false,
  "gitlens.heatmap.locations": ["gutter", "overview"],
  "gitlens.defaultDateStyle": "absolute",
  "html-css-class-completion.enableEmmetSupport": true,
  "html.format.templating": true,
  "css.enabledLanguages": ["html", "django-html"],
  "notebook.cellToolbarLocation": {
    "default": "right",
    "jupyter-notebook": "left"
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": true,
  "editor.guides.highlightActiveIndentation": true,
  "editor.guides.indentation": true,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "telemetry.telemetryLevel": "off",
  "mssql.connections": [],
  "github.copilot.enable": {
    "*": false,
    "yaml": true,
    "plaintext": false,
    "markdown": false,
    "javascript": true,
    "csharp": true,
    "vue": true,
    "cpp": true,
    "python": true,
    "json": true,
    "editorconfig": true,
    "css": true,
    "properties": true
  },
  "editor.inlineSuggest.enabled": true,
  "git.pruneOnFetch": true,
  "git.showActionButton": {
    "commit": false,
    "publish": false,
    "sync": false
  },
  // "[csharp]": {
  //   "editor.defaultFormatter": "ms-dotnettools.csharp"
  // },
  "csharp.format.enable": true,
  "csharp.semanticHighlighting.enabled": true,
  "html-css-class-completion.includeGlobPattern": "**/*.{css,html,vue,scss}",
  "gitlens.views.repositories.showIncomingActivity": true,
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "livePreview.serverKeepAliveAfterEmbeddedPreviewClose": 0,
  "rpc.buttonEnabled": true,
  "rpc.removeLowerDetailsIdling": false,

  "editor.semanticHighlighting.enabled": false,
  "window.titleBarStyle": "custom",
  "window.menuBarVisibility": "compact",
  "workbench.colorCustomizations": {},
  "rapidapi.codegen.default": "javascript",
  "tailwindCSS.emmetCompletions": true,
  "tailwindCSS.includeLanguages": {
    "vue": "html",
    "vue-html": "html"
  },
  "python.formatting.provider": "yapf",
  "editor.formatOnSave": true
}

```

**Reproduction URL**

https://github.com/wrench1815/tail_ext_repro

**Describe your issue**

The Intellisense is not working in VS Code. Looking at extension output, It shows following:
```
[Global] Creating projects: [{"folder":"/home/wrench1815/Documents/git/portfolio","configPath":"/home/wrench1815/Documents/git/portfolio/tailwind.config.js","isUserConfigured":false,"documentSelector":[{"pattern":"/home/wrench1815/Documents/git/portfolio/tailwind.config.js","priority":0},{"pattern":"/home/wrench1815/Documents/git/portfolio/**","priority":3}]},{"folder":"/home/wrench1815/Documents/git/portfolio","configPath":"/home/wrench1815/Documents/git/portfolio/.nuxt/tailwind.config.cjs","isUserConfigured":false,"documentSelector":[{"pattern":"/home/wrench1815/Documents/git/portfolio/.nuxt/tailwind.config.cjs","priority":0},{"pattern":"/home/wrench1815/Documents/git/portfolio/components/**/*.{vue,js,ts}","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/layouts/**/*.vue","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/pages/**/*.vue","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/composables/**/*.{js,ts}","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/plugins/**/*.{js,ts}","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/App.{js,ts,vue}","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/app.{js,ts,vue}","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/Error.{js,ts,vue}","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/error.{js,ts,vue}","priority":1},{"pattern":"/home/wrench1815/Documents/git/portfolio/.nuxt/**","priority":3},{"pattern":"/home/wrench1815/Documents/git/portfolio/**","priority":4}]}]
[Global] Adding watch patterns: /home/wrench1815/Documents/git/portfolio/tailwind.config.js, /home/wrench1815/Documents/git/portfolio, /home/wrench1815/Documents/git, /home/wrench1815/Documents, /home/wrench1815, /home, /
[Global] Adding watch patterns: /home/wrench1815/Documents/git/portfolio/.nuxt/tailwind.config.cjs, /home/wrench1815/Documents/git/portfolio/.nuxt
[.nuxt/tailwind.config.cjs] Initializing...
[.nuxt/tailwind.config.cjs] Loaded Tailwind CSS config file: /home/wrench1815/Documents/git/portfolio/.nuxt/tailwind.config.cjs
[.nuxt/tailwind.config.cjs] Loaded postcss v8.4.19: /home/wrench1815/Documents/git/portfolio/node_modules/postcss
[.nuxt/tailwind.config.cjs] Loaded tailwindcss v3.2.2: /home/wrench1815/Documents/git/portfolio/node_modules/tailwindcss
[.nuxt/tailwind.config.cjs] Building...
[Error - 1:51:31 PM] Tailwind CSS: Cannot read properties of null (reading '__isOptionsFunction')
TypeError: Cannot read properties of null (reading '__isOptionsFunction')
    at /home/wrench1815/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:9720
    at Array.map (<anonymous>)
    at /home/wrench1815/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:9705
    at _require.Ks.default.require (/home/wrench1815/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:178:45097)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/wrench1815/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:712:10084
    at Generator.next (<anonymous>)
    at /home/wrench1815/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:1:1219
    at new Promise (<anonymous>)
    at Xt (/home/wrench1815/.vscode/extensions/bradlc.vscode-tailwindcss-0.9.1/dist/tailwindServer.js:1:1039)
```

Also Im using [Daisy UI](https://daisyui.com) instead of plain TailwinCSS along with [TailwindCSS Nuxt Module](https://tailwindcss.nuxtjs.org).

Related issue in tailwindcss repository https://github.com/tailwindlabs/tailwindcss/issues/9657

**Comment by bradlc** [comment]
Hey @wrench1815, please can you share a GitHub repository that I can open in VS Code to reproduce the issue

**Comment by cryks** [comment]
It seems that the `@tailwindcss/typography` plugin and `@nuxtjs/tailwindcss` are incompatible.
The build output `.nuxt/tailwind.config.cjs` contains `plugins: [ null ]`, which seems to be causing an error.

**Comment by wrench1815** [comment]
@bradlc here https://github.com/wrench1815/tail_ext_repro

**Comment by wrench1815** [comment]
@cryks actually the thing is it's working normal if I downgrade the tailwind extension to version 0.8.7.

**Comment by bradlc** [comment]
Ok I understand now. It seems that `.nuxt/tailwind.config.cjs` is a resolved version of your config, which you can expose to your app to access config values. It is not an actual valid Tailwind config file that is meant to be used by the `tailwindcss` module. In that case my recommendation would be to exclude the `.nuxt` directory in the extension settings:

```diff
  "tailwindCSS.files.exclude": [
    "**/.git/**",
    "**/node_modules/**",
    "**/.hg/**",
    "**/.svn/**",
+   "**/.nuxt/**"
  ]
```

This will prevent the extension from picking up the `.nuxt/tailwind.config.cjs` file 👍

**Comment by vanling** [comment]
@bradlc when ignoring that nuxt file does intelisense work again for you?

**Comment by arafays** [comment]
> Ok I understand now. It seems that `.nuxt/tailwind.config.cjs` is a resolved version of your config, which you can expose to your app to access config values. It is not an actual valid Tailwind config file that is meant to be used by the `tailwindcss` module. In that case my recommendation would be to exclude the `.nuxt` directory in the extension settings:
> 
> ```diff
>   "tailwindCSS.files.exclude": [
>     "**/.git/**",
>     "**/node_modules/**",
>     "**/.hg/**",
>     "**/.svn/**",
> +   "**/.nuxt/**"
>   ]
> ```
> 
> This will prevent the extension from picking up the `.nuxt/tailwind.config.cjs` file 👍

its stuff like this I have fewer hairs and feel like their will be special place in heaven for people who cleanup other people's messes

**Comment by nazar1ua** [comment]
Here is the right fix: https://tailwindcss.nuxt.dev/tailwind/config#config-option

**Comment by nazar1ua** [comment]
@bradlc there is problem with `resolveConfig.js` file in `tailwindcss` package. Nuxt tailwind module contains this code:
https://github.com/nuxt-modules/tailwindcss/blob/c32cadba15dc5cf0242c8f1b7870987a494454ac/src/module.ts#L142-L148

```js
console.log(resolvedConfig.plugins)
```

The output is:
```
[
  [Function: optionsFunction] {
    __isOptionsFunction: true,
    __pluginFunction: [Function (anonymous)],
    __configFunction: [Function (anonymous)]
  },
  [Function: optionsFunction] {
    __isOptionsFunction: true,
    __pluginFunction: [Function (anonymous)],
    __configFunction: [Function: configFunction]
  }
]
```

And then, `JSON.stringify` turns it into [null, null]

**Comment by KeoneSomers** [comment]
In order to get tailwind intellisense working for me I just added a tailwind.config .js file to the root of my project.
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.html", "./src/**/*.vue", "./src/**/*.jsx"],
    theme: {
        extend: {},
    },
    plugins: [require("@tailwindcss/forms")],
};
```

And in my nuxt.config.ts:
```ts
modules: ["@nuxtjs/tailwindcss"],
```

**Comment by bradley-varol** [comment]
> m with `resolveConfig.js` file in `tailwindcss` package. Nuxt tailwind module cont

doing this completely broke my intellisense - I was missing the `prose` classes before, but now I have no classes :D

**Comment by zackha** [comment]
If you are working with nuxt3, you can try this.

Add the following configuration to your `.vscode/settings.json file`, so that Tailwind directives have proper autocomplete, syntax highlighting, and linting:

```
"tailwindCSS.experimental.configFile": ".nuxt/tailwind.config.cjs"
"files.associations": {
    "*.css": "tailwindcss"
}
```

detailed: [link](https://tailwindcss.nuxt.dev/tailwind/editor-support)
