### ISSUE TITLE
bug: Can't resolve 'fs/promises'

### ISSUE THREAD

**Issue by AdditionAddict** [tailwindlabs/tailwindcss-intellisense#743]
**What version of Tailwind CSS IntelliSense are you using?**

0.9.9

**What version of Tailwind CSS are you using?**

^3.0.2

**What package manager are you using?**

pnpm 7.5.2

**What operating system are you using?**

Windows

**Tailwind config**

```js
const { createGlobPatternsForDependencies } = require('@nrwl/angular/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

**VS Code settings**

```json
{
  "[javascript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "prettier.printWidth": 70,
  "prettier.singleQuote": true,
  "files.associations": {
    "*.ts": "typescript",
    "*.html": "html"
  },
  "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
  "python.linting.enabled": true,
  "python.linting.ignorePatterns": ["app/*", "scoped_session"],
  "python.linting.pycodestyleEnabled": true,
  "editor.formatOnSave": true,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "angular.disableAutomaticNgcc": true,
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "diffEditor.ignoreTrimWhitespace": false,
  "window.zoomLevel": 1,
  "extensions.ignoreRecommendations": true,
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "[python]": {
    "editor.formatOnType": true
  },
  "[yaml]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.minimap.enabled": false
}
```

**Reproduction URL**

https://github.com/AdditionAddict/nx-tutorials/tree/extension-issue-743

**Describe your issue**

I get no intellisense and an output error in an Nx monorepo with an Angular application

Steps 
- Go to apps\fireship-tailwind\src\app\app.component.ts
- Edit `<h1>` to `<h1 class="text-center">`

Error below occurs in Output

```
[apps\fireship-tailwind\tailwind.config.js] Building...
[Error - 2:38:54 PM] Tailwind CSS: Can't resolve 'fs/promises' in 'C:\Users\andrewa\Documents\ProofOfConceptApps\nx-tutorials\node_modules\.pnpm\nx@15.8.9\node_modules\nx\src\daemon\client'
Error: Can't resolve 'fs/promises' in 'C:\Users\andrewa\Documents\ProofOfConceptApps\nx-tutorials\node_modules\.pnpm\nx@15.8.9\node_modules\nx\src\daemon\client'
    at h (c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:130:7129)
    at c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:131:713
    at c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:134:401
    at eval (eval at create (c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:5:78), <anonymous>:15:1)
    at c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:134:401
    at eval (eval at create (c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:5:78), <anonymous>:27:1)
    at c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:134:7650
    at c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:134:401
    at eval (eval at create (c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:5:78), <anonymous>:15:1)
    at c:\Users\andrewa\.vscode\extensions\bradlc.vscode-tailwindcss-0.9.9\dist\tailwindServer.js:134:401
```

**Other info**

Node v16.17.1

**Comment by n-mcnally** [comment]
Same issue on MacOS 13.1

**Comment by IamSAL** [comment]
I faced this issue while using in a Nx monorepo.

temporary fix is to comment the use of `createGlobPatternsForDependencies(__dirname)`, until #745 gets into production.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/34414233/228123554-f909edba-231e-4c3f-b21d-b346370e2902.png">

**Comment by AdditionAddict** [comment]
v0.9.10 released
